### ISSUE TITLE
普通にnpm installするとエラーになる

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vektor-wp-libraries#139]
ここで使われているNode.jsのバージョンが古いままである一方で、一部のパッケージがNode.js 18以上を必要としているため、依存関係のインストールやビルド時に問題が発生しているようです。

## エラー原文
```
mt@matsudakeinoMacBook-Air vektor-wp-libraries % npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated osenv@0.1.5: This package is no longer supported.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated npmlog@6.0.2: This package is no longer supported.
npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated gauge@4.0.4: This package is no longer supported.
npm WARN deprecated read-package-json@6.0.0: This package is no longer supported. Please use @npmcli/package-json instead.
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm WARN deprecated are-we-there-yet@1.1.5: This package is no longer supported.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated @babel/plugin-proposal-private-methods@7.13.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
npm WARN deprecated node-sass@4.14.1: Node Sass is no longer supported. Please use sass or sass-embedded instead.
npm WARN deprecated @babel/plugin-proposal-json-strings@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
npm WARN deprecated @babel/plugin-proposal-dynamic-import@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
npm WARN deprecated @babel/plugin-proposal-export-namespace-from@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.13.12: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.13.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated rimraf@4.1.2: Please upgrade to 4.3.1 or higher to fix a potentially damaging issue regarding symbolic link following. See https://github.com/isaacs/rimraf/issues/259 for details.
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.13.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated gauge@2.7.4: This package is no longer supported.
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated uuid@1.4.2: Please upgrade to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! code 1
npm ERR! path /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /Users/mt/.nvm/versions/node/v16.20.2/bin/node /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/mt/.nvm/versions/node/v16.20.2/bin/node',
npm ERR! gyp verb cli   '/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.20.2 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2.7" in the PATH
npm ERR! gyp verb which failed Error: not found: python2.7
npm ERR! gyp verb which failed     at getNotFoundError (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:13:12)
npm ERR! gyp verb which failed     at F (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:68:19)
npm ERR! gyp verb which failed     at E (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:80:29)
npm ERR! gyp verb which failed     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:89:16
npm ERR! gyp verb which failed     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/isexe/index.js:42:5
npm ERR! gyp verb which failed     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb which failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb which failed  python2.7 Error: not found: python2.7
npm ERR! gyp verb which failed     at getNotFoundError (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:13:12)
npm ERR! gyp verb which failed     at F (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:68:19)
npm ERR! gyp verb which failed     at E (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:80:29)
npm ERR! gyp verb which failed     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:89:16
npm ERR! gyp verb which failed     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/isexe/index.js:42:5
npm ERR! gyp verb which failed     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb which failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb which failed   code: 'ENOENT'
npm ERR! gyp verb which failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp ERR! System Darwin 23.5.0
npm ERR! gyp ERR! command "/Users/mt/.nvm/versions/node/v16.20.2/bin/node" "/Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/mt/Local Sites/vk-lightning-pro/app/public/wp-content/vektor-wp-libraries/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.20.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mt/.npm/_logs/2024-08-16T05_41_26_826Z-debug-0.log
```

**Comment by mtdkei** [comment]
とりあえずこちらの環境のnodeを下げたりPythonの2.7を入れてみたり色々ごちゃごちゃしてるうちにnpm installができるようにはなってます。
